import { Inter } from "next/font/google";
import "@styles/globals.css";
import Nav from "@components/nav";
import Provider from "@components/provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className="main">
            <div className="gradient"></div>
          </div>

          <main className="app">
            <Nav />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
